version: '3.8'
services:
  admin_panel_db:
    image: postgres:13
    container_name: admin_panel_db
    env_file:
      - ./.env.db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 2s
      timeout: 2s
      retries: 5
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - movies_network

  admin_panel_django_gunicorn:
    build:
      context: ./movies_admin
    volumes:
      - static_volume:/home/app/movies_admin/staticfiles
      - media_volume:/home/app/movies_admin/mediafiles
      - ./tmp/logs/app:/home/app/movies_admin/log
    depends_on:
      admin_panel_db:
        condition: service_healthy
    container_name: django_container
    restart: unless-stopped
    env_file:
      - ./movies_admin/.env
    networks:
      - movies_network

  admin_panel_nginx:
    image: nginx:1.22.1
    container_name: admin_panel_nginx
    volumes:
      - static_volume:/home/app/movies_admin/staticfiles
      - media_volume:/home/app/movies_admin/mediafiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./tmp/logs/nginx/:/var/log/nginx/
    ports:
      - "80:80"
    depends_on:
      - admin_panel_django_gunicorn
    networks:
      - movies_network

volumes:
  static_volume:
  media_volume:
  postgresql_volume:

networks:
  movies_network:
    external: true
